### ISSUE TITLE
Unauthorized Error on implementation

### ISSUE THREAD

**Issue by noorfatima15** [XeroDays/live_currency_rate#2]
after implementing and even passing hard coded values still get this error
val  statuas: false message:Not Authorized. Return with Reponse code : 500 value:0.0

**Comment by XeroDays** [comment]
Hi @noorfatima15 ,
Thanks for noticing, its been a while i havent worked on it, seems like apis are outdated. please do give me some time to update it. 

Thanks.

**Comment by XeroDays** [comment]
@noorfatima15 Can you please check now! its fixed. Thanks
