### ISSUE TITLE
Error: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by njaistudio** [XeroDays/live_currency_rate#4]
I am getting this error since yesterday. Please fix it.

**Comment by XeroDays** [comment]
Checking.

**Comment by XeroDays** [comment]
@njaistudio  this is due to FREE API quote, yesterday requests were more than 45,000. Our server didnt expected this much requests. but anyway.. Thanks for creating this issue.. will fix this by EOD

**Comment by XeroDays** [comment]
@njaistudio  **Bug Fixed.** Please check.

**Comment by njaistudio** [comment]
It work. Thank you so much
